import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

// Client component to handle hydration mismatches caused by browser extensions
function BodyContent({ children }: { children: React.ReactNode }) {
  return (
    <body
      className="antialiased flex flex-col min-h-screen"
      suppressHydrationWarning={true}
    >
      <NavBar />
      <main className="flex-grow">
        {children}
      </main>
      <Footer />
    </body>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <BodyContent>
        {children}
      </BodyContent>
    </html>
  );
}
