import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Client component to handle hydration mismatches caused by browser extensions
function BodyContent({ children }: { children: React.ReactNode }) {
  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      suppressHydrationWarning={true}
    >
      <NavBar />
      <main className="flex-grow">
        {children}
      </main>
      <Footer />
    </body>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <BodyContent>
        {children}
      </BodyContent>
    </html>
  );
}
